WC-1234567: '[{"name": "WC-1234567-1", "type": "RL-BOARD", "feed": "RL-0CEC53B267AC-0"},
  {"name": "WC-1234567-2", "type": "RL-BOARD", "feed": "RL-0CEC53B267AC-1"}, {"name":
  "WC-1234567-3", "type": "BUILTIN", "feed": "BUILTIN"}, {"name": "WC-1234567-4",
  "type": "BUILTIN", "feed": "BUILTIN"}, {"name": "WC-1234567-5", "type": "BUILTIN",
  "feed": "BUILTIN"}, {"name": "WC-1234567-6", "type": "BUILTIN", "feed": "BUILTIN"},
  {"name": "WC-1234567-7", "type": "BUILTIN", "feed": "BUILTIN"}, {"name": "WC-1234567-8",
  "type": "BUILTIN", "feed": "BUILTIN"}]'
