WC-12345678: '[{"name": "WC-12345678-1", "type": "NTC", "feed": "1", "multiplier":
  1.0, "summer": 0.0}, {"name": "WC-12345678-2", "type": "NTC", "feed": "2", "multiplier":
  1.0, "summer": 0.0}, {"name": "WC-12345678-3", "type": "NTC", "feed": "3", "multiplier":
  1.0, "summer": 0.0}, {"name": "WC-12345678-4", "type": "NTC", "feed": "4", "multiplier":
  1.0, "summer": 0.0}, {"name": "WC-12345678-5", "type": "NTC", "feed": "5", "multiplier":
  1.0, "summer": 0.0}, {"name": "WC-12345678-6", "type": "NTC", "feed": "6", "multiplier":
  1.0, "summer": 0.0}, {"name": "WC-12345678-7", "type": "NTC", "feed": "7", "multiplier":
  1.0, "summer": 0.0}, {"name": "WC-12345678-8", "type": "NTC", "feed": "8", "multiplier":
  1.0, "summer": 0.0}]'
