WC-123456: '[{"name": "WC-123456-1", "master": "NO FOLLOW"}, {"name": "WC-123456-2",
  "master": "NO FOLLOW"}, {"name": "WC-123456-3", "master": "NO FOLLOW"}, {"name":
  "WC-123456-4", "master": "NO FOLLOW"}, {"name": "WC-123456-5", "master": "NO FOLLOW"},
  {"name": "WC-123456-6", "master": "NO FOLLOW"}, {"name": "WC-123456-7", "master":
  "NO FOLLOW"}, {"name": "WC-123456-8", "master": "NO FOLLOW"}]'
