# Example services.yaml entry

schedule:
  # Description of the service
  description: For scheduling a wiringcentral thermostat.
  # Different fields that your service accepts
  fields:
    # Key of the field
    entity_id:
      # Description of the field
      description: Name of the entities to set
      # Example value that can be passed for this field
      example: "climate.wiringcentral"
    data:
      description: Schedule data as a dictionary
      example: {}

schedule_clear:
  # Description of the service
  description: For clearing the thermostat schedules.
  # Different fields that your service accepts
  fields:
    # Key of the field
    entity_id:
      # Description of the field
      description: Name of the entity to clear the schedule
      # Example value that can be passed for this field
      example: "climate.wiringcentral"
    data:
      description: Empty
      example: {}

masterslave:
  # Description of the service
  description: For creating or updating master slave configuration.
  # Different fields that your service accepts
  fields:
    # Key of the field
    board_id:
      # Description of the field
      description: Name of the board to read from the configuration
      # Example value that can be passed for this field
      example: "climate.wiringcentral"